---
title: "Visualization"
author: "Xieyu Liu"
date: "2026-10-01"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

Now we have everything we need!

```{r}
weather_df
```

let's make a scatterplot!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))+
  geom_point()
```

I always like the dataframe first

```{r}
ggp_temp_scatterplot =
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_temp_scatterplot
```

let's make this a bit fancier...

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .25) + # alpha makes it transparent
  geom_smooth(se = F) # see a trend, se = F means no error bars
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .25) + # alpha makes it transparent, only apply points in different color, there will be only one smooth line
  geom_smooth(se = F) # see a trend, se = F means no error bars
```

The aesthetics are up to you

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_smooth(se = F)
```

Show faceting

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha = .5) +
  facet_grid(name~ .) #. ~ name horizontal layout; name~ . vertical layout, classic version
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point(alpha = .5) +
  facet_grid(cols = vars(name)) #new version
```

Let's look at something else.

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se=F) +
  facet_grid(. ~ name)
```

make a plot of central park tmax vs tmin only, and convert temperatures to fahrenheit.

```{r}
weather_df |>
  filter (name == "CentralPark_NY") |>
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin * (9/5) + 32
  ) |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

